### ISSUE TITLE
"Class not found : Assets" compilation error

### ISSUE THREAD

**Issue by JeriXNet** [unihx/unihx#14]
I'm using latest haxe build for windows from [build.haxe.org](http://build.haxe.org/)

**Comment by waneck** [comment]
When does this message show? Can you try using the `tmp` branch from unihx?

**Comment by JeriXNet** [comment]
It shows in sublime build results panel after I press ctrl+enter.
I'll try `tmp` and let you know about how it goes.

**Comment by JeriXNet** [comment]
No, still same message:
![2015-01-17_032703](https://cloud.githubusercontent.com/assets/7815518/5786602/efdcbcb8-9df8-11e4-9d41-f248130552fc.jpg)

**Comment by waneck** [comment]
The build.hxml provided should not be enough to compile through sublime. You can use alt+tab to the Unity window to force its compilation there.

**Comment by waneck** [comment]
Hm. It seems a problem with sublime `.hxml` parsing - it should be 'unity_std_target=Standard Assets'

Anyway Alt+tab on the unity project window should work on the tmp branch (be sure to do `haxelib run unihx init path/to/Assets` again)

**Comment by JeriXNet** [comment]
> Anyway Alt+tab on the unity project window should work on the tmp branch (be sure to do haxelib run unihx init path/to/Assets again)

What do you mean by that? I should add hx sources to Assets folder, run unihx init on `tmp` branch and just load project in Unity?

**Comment by waneck** [comment]
Yeah. That should work:
1) use the tmp branch
2) run haxelib run unihx init path/to/your/unity/project
3) open the project in unity

Any .hx file you have there will be compiled - just like it happens with .cs files. You will also be able to drag & drop the .hx files into GameObjects 

The `development` branch can also work though - it's just that I'm working for so long time in the `tmp` I'm not sure anymore what is implemented on the `development`.

**Comment by JeriXNet** [comment]
And what should I do when I modify any haxe file? Run `unihx init` again or maybe `haxe build.xml`?

**Comment by waneck** [comment]
You can do an alt+tab into the unity project - like you would do with any `.cs` or `.js` file. You can also force a compilation by clicking on the `build.hxml` file on Unity and clicking on the `Force compilation` button

**Comment by JeriXNet** [comment]
Yes, that's working perfectly!
It's very nice feature!
How it was achieved? Editor scripts?

**Comment by waneck** [comment]
Great! It's done through an AssetProcessor: https://github.com/unihx/unihx/blob/tmp/src/unihx/pvt/editor/AssetProcessor.hx

I'll close this issue now. Please report the .hxml parsing issue to the sublime plugin if you don't have autocompletion on sublime!

**Comment by JeriXNet** [comment]
No, `autocompletion`, `Goto definition (Haxe)` and `Show type (Haxe)` works in sublime.
But probably should report about this `-D unity_std_target=Standard Assets` parsing problem...
